#!/usr/bin/env bash
# Install and configure HAproxy
apt-get update
apt-get -y install haproxy=1.6.\*
echo "frontend web_front
   bind *:80
   mode http
   default_backend web-backend
   backend web-backend
   balance roundrobin
   mode http
   server web1 35.237.50.4:80 check
   server web2 54.221.40.23:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
