#!/usr/bin/env bash
#Program that prints FizzBuzz sequence
for a in {1..100}
do
    if [ $((a % 5)) -eq 0 -a $((a % 3)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((a % 5)) -eq 0 ]
    then
	echo "Buzz"
    elif [ $((a % 3)) -eq 0 ]
    then
	echo "Fizz"
    else
	echo "$a"
    fi
done
