#!/usr/bin/env bash
# Script that displays number/string using while loop with conditions
a="1"

while ((a <= 20)); do
        echo $a
    case $a in
	4)
	    echo "bad luck from China";;
	9)
	    echo "bad luck from Japan";;
	17)
	    echo "bad luck from Italy";;
    esac
    ((a++))
done
